Repository heliopython/heliopy, pull requests merged in 2018-03, with the labels that each got.

#377 Added JUNO Kernel
  heliopy/data/spice.py
Labels: spice

#379 Added Helios 1_Predicted Kernel
  heliopy/data/spice.py
Labels: spice

#380 Updated Changelog
  CHANGES.rst
Labels: docs

#382 Download susnpot data to data directory
  .gitignore
  heliopy/data/sunspot.py
Labels: data import

#383 Add list of available kernels to docs
  heliopy/data/spice.py
Labels: docs

#385 Clean up susnpot number example
  examples/plot_sunspot.py
Labels: docs

#359 Add some more swics data import functions
  CHANGES.rst
  heliopy/data/ace.py
  heliopy/data/test/test_data.py
Labels: data import

#390 Make spice kernel table look nicer
  heliopy/data/spice.py
Labels: docs, spice

#389 Update changelog for version 0.5
  CHANGES.rst
Labels: docs

#393 Change theme colour
  doc/heliopy_theme/static/style.css
Labels: docs

#392 Add twitter link to doc footer
  doc/heliopy_theme/layout.html
Labels: docs

#391 Add link to kernel table
  heliopy/data/spice.py
Labels: docs

#386 Updated Artemis doc file
  doc/source/data/artemis.rst
  doc/source/data/cassini.rst
  doc/source/data/cluster.rst
  doc/source/data/helios.rst
  doc/source/data/helper.rst
  doc/source/data/imp.rst
  doc/source/data/messenger.rst
  doc/source/data/mms.rst
  doc/source/data/sunspot.rst
  doc/source/data/ulysses.rst
  doc/source/data/wind.rst
Labels: docs

#398 Update to newest CDF version in travis build
  .travis.yml
Labels: testing
