Repository heliopython/heliopy, pull requests merged in 2018-04, with the labels that each got.

#400 Fix cassini urls
  heliopy/data/cassini.py
Labels: data import

#401 Try travis build without sudo
  .travis.yml
Labels: testing

#399 Improve FTP code
  heliopy/data/util.py
  setup.cfg
Labels: testing

#387 Added several kernels
  heliopy/data/spice.py
Labels: spice

#404 Convert Ulysses downloading to load
  heliopy/data/ulysses.py
  heliopy/data/util.py
Labels: data import

#407 Some small Ulysses fixes
  heliopy/data/ulysses.py
Labels: data import

#408 Overhaul spice data module
  heliopy/data/spice.py
  heliopy/data/test/test_data.py
  heliopy/test/test_spice.py
Labels: data import, spice

#409 Clean up docs
  doc/heliopy_theme/static/style.css
  doc/source/data/ace.rst
  doc/source/data/artemis.rst
  doc/source/data/cassini.rst
  doc/source/data/cluster.rst
  doc/source/data/helios.rst
  doc/source/data/helper.rst
  doc/source/data/imp.rst
  doc/source/data/index.rst
  doc/source/data/messenger.rst
  doc/source/data/mms.rst
  doc/source/data/sunspot.rst
  doc/source/data/ulysses.rst
  doc/source/data/wind.rst
Labels: docs

#410 Add some more spice kernels
  heliopy/data/spice.py
  heliopy/spice.py
  heliopy/test/test_spice.py
Labels: spice

#413 Improve load documentation
  heliopy/data/util.py
Labels: docs

#414 Add issue linking to changelog
  CHANGES.rst
  doc/source/conf.py
  requirements/docs.txt
Labels: docs

#423 Add versionfile_build
  setup.cfg
Labels: Docs

#426 Add docs for installing conda
  doc/source/guide/installing.rst
Labels: Docs

#429 Add citing page
  doc/source/guide/citing.rst
  doc/source/guide/configuring.rst
  doc/source/guide/index.rst
  doc/source/guide/installing.rst
Labels: Docs

#430 Update landing page
  doc/source/index.rst
Labels: Docs

#432 Update release guide
  doc/source/development/release.rst
Labels: Docs

#431 Update changelog for 0.5.1
  CHANGES.rst
Labels: Docs
