Repository heliopython/heliopy, pull requests merged in 2018-06, with the labels that each got.

#483 Try activating pip cahce on travis
  .travis.yml
Labels: Testing

#490 Updated fpi_dis_moms
  heliopy/data/mms.py
Labels: Bug, Data import

#501 Try to plot spice example in doc build
  doc/source/conf.py
  examples/plot_spice_orbit.py
  requirements/docs.txt
Labels: Docs

#498 Units Documentation
  CHANGES.rst
  doc/source/conf.py
  doc/source/data/index.rst
  examples/plot_timeseries.py
  examples/timeseries.py
  heliopy/data/ace.py
  heliopy/data/artemis.py
  heliopy/data/cassini.py
  heliopy/data/helios.py
  heliopy/data/imp.py
  heliopy/data/ulysses.py
  heliopy/data/util.py
  heliopy/data/wind.py
Labels: Docs, Units

#504 Removed multi_index example.
  examples/plot_multi_index.py
Labels: Docs

#505 Remove dev testing on travis
  .travis.yml
Labels: Testing

#509 Adding default thumbnail
  doc/source/conf.py
Labels: Docs

#513 Added cassini.mag_hires units
  heliopy/data/cassini.py
Labels: Units

#520 Doc fixes
  .gitignore
  doc/Makefile
  heliopy/data/helios.py
  heliopy/data/helper.py
Labels: Docs

#521 Some doc fixes
  README.md
  doc/source/data/index.rst
  doc/source/guide/installing.rst
  doc/source/index.rst
Labels: Docs

#511 Migrated SPICE kernels from previous spice.py
  heliopy/data/spice.py
Labels: Data import, Spice
