Repository heliopython/heliopy, pull requests merged in 2018-05, with the labels that each got.

#434 Convert artemis.fgm to util.process
  heliopy/data/artemis.py
  heliopy/data/test/test_data.py
  heliopy/data/util.py
Labels: Data import, Enhancement

#436 Added units to Ulysses ( except FGM Hires ) and modified util function ( units_attach )
  heliopy/data/test/test_data.py
  heliopy/data/ulysses.py
  heliopy/data/util.py
Labels: Units

#437 Removed units from ACE.mfi_h0
  heliopy/data/ace.py
  heliopy/data/test/test_data.py
Labels: Units

#440 Added a TimeSeries Plot Example
  examples/plot_timeseries.py
Labels: Units

#447 Add favicon to website
  artwork/favicon.ico
  doc/source/conf.py
Labels: Docs

#448 Add logo to website
  doc/heliopy_theme/navbar.html
  doc/heliopy_theme/static/navbar.svg
  doc/heliopy_theme/static/style.css
  doc/heliopy_theme/theme.conf
Labels: Docs

#449 Put logo in readme
  README.md
  artwork/logo_rectangle.svg
Labels: Docs

#452 Remove a mention of HelioPy from doc sidebar
  doc/heliopy_theme/docsidebar.html
  logo/logo_base.svg
  logo/logo_riot.png
Labels: Docs

#461 Add doc tests
  .circleci/config.yml
  doc/heliopy_theme/static/copybutton.js
  doc/source/conf.py
  doc/source/coords.rst
  doc/source/development/testing.rst
  heliopy/coordinates/__init__.py
  heliopy/coordinates/frames.py
Labels: Docs

#462 Added doc for units
  heliopy/data/util.py
Labels: Docs, Units

#465 Convert _load_local to only take a full filepath
  heliopy/data/cassini.py
  heliopy/data/util.py
Labels: Data import

#468 Clean up process docstring
  heliopy/data/util.py
Labels: Docs

#454 Added a module to get units from CDF
  heliopy/data/ace.py
  heliopy/data/test/test_data.py
  heliopy/data/util.py
Labels: Units

#469 Added units for helios.merged
  heliopy/data/helios.py
  heliopy/data/test/test_data.py
Labels: Units

#463 Add documentation for transformations
  doc/source/coords.rst
  heliopy/coordinates/__init__.py
  heliopy/coordinates/frames.py
  heliopy/coordinates/test/test_transformations.py
  heliopy/coordinates/transformations.py
Labels: Docs

#479 Close files if they are still open
  heliopy/data/util.py
Labels: Bug, Data import

#480 Fix helios docstrings
  CHANGES.rst
  heliopy/data/helios.py
Labels: Docs
