Repository heliopython/heliopy, pull requests merged in 2019-06, with the labels that each got.

#719 Change allowed_probes of mms.py
  heliopy/data/mms.py
  heliopy/data/test/test_mms.py
Labels: Bug, Data import

#729 Add towncrier support for changelogs
  changelog/719.bugfix.rst
  changelog/726.bugfix.rst
  changelog/README.rst
  pyproject.toml
Labels: Docs

#734 Pin bootstrap version
  requirements/docs.txt
Labels: Docs

#733 Add docs for adding data sources
  doc/source/data/index.rst
  heliopy/data/util.py
Labels: Docs, Needs backport

#739 Update 0.8 changes for towncrier
  CHANGES.rst
  changelog/714.breaking
  changelog/714.feature
  changelog/715.feature
  changelog/719.bugfix.rst
  changelog/726.bugfix.rst
  changelog/README.rst
  pyproject.toml
Labels: Docs

#740 0.8.0 changelog
  CHANGES.rst
  changelog/714.breaking
  changelog/714.feature
  changelog/715.feature
Labels: Docs
