Repository heliopython/heliopy, pull requests merged in 2020-02, with the labels that each got.

#841 Add "include" keyword to cdf2df
  heliopy/data/util.py
Labels: Needs changelog

#844 Speedup cdf loading
  heliopy/data/util.py
  pytest.ini
Labels: Needs changelog

#846 Update heliopy.data docstrings
  heliopy/data/ace.py
  heliopy/data/artemis.py
  heliopy/data/cassini.py
  heliopy/data/dscovr.py
  heliopy/data/imp.py
  heliopy/data/mms.py
  heliopy/data/omni.py
  heliopy/data/spice.py
  heliopy/data/sunspot.py
  heliopy/data/ulysses.py
  heliopy/data/wind.py
Labels: Data import, Docs, Needs changelog

#845 More CDF speedup
  heliopy/data/util.py
Labels: Enhancement

#847 Some more CDF loading speedup
  heliopy/data/util.py
Labels: Needs changelog

#848 Automatically detect and fill bad values in CDF files
  heliopy/data/ace.py
  heliopy/data/helios.py
  heliopy/data/imp.py
  heliopy/data/psp.py
  heliopy/data/util.py
  heliopy/data/wind.py
Labels: Data import, Enhancement, Needs changelog

#849 Bump test timeout in test_wind.py
  heliopy/data/test/test_wind.py
  pytest.ini
Labels: Testing

#842 Add PSP FIELDS hires data
  heliopy/data/helper.py
  heliopy/data/psp.py
  heliopy/data/test/test_psp.py
Labels: Data import, Needs changelog

#852 Add 0.10.0 changelog
  changelog/828.feature.rst
  changelog/831.feature.rst
  changelog/841.feature.rst
  changelog/842.feature.rst
  changelog/844.feature.rst
  changelog/845.feature.rst
  changelog/846.doc.rst
  changelog/847.feature.rst
  changelog/848.feature.rst
Labels: Docs

#853 Add changelog for 0.10.0
  CHANGES.rst
  changelog/828.feature.rst
  changelog/831.feature.rst
  changelog/841.feature.rst
  changelog/842.feature.rst
  changelog/844.feature.rst
  changelog/845.feature.rst
  changelog/846.doc.rst
  changelog/847.feature.rst
  changelog/848.feature.rst
Labels: Docs

#855 Update release docs
  doc/source/development/release.rst
Labels: Docs
